
all:
	$(MAKE) -C ee
	$(MAKE) -C iop

lib:
	$(MAKE) -C ee lib
	$(MAKE) -C iop lib

samples:
	$(MAKE) -C ee samples
	$(MAKE) -C iop samples

clean:
	$(MAKE) -C ee clean
	$(MAKE) -C iop clean

utils:
	$(MAKE) -C iop utils
