all:
	$(MAKE) -C simple
	$(MAKE) -C hi-res
	$(MAKE) -C texture
	$(MAKE) -C multi-buffer
	$(MAKE) -C multi-pipe
	$(MAKE) -C font

clean:
	$(MAKE) -C simple clean
	$(MAKE) -C hi-res clean
	$(MAKE) -C texture clean
	$(MAKE) -C multi-buffer clean
	$(MAKE) -C multi-pipe clean
	$(MAKE) -C font clean
