# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.
#
# $Id: Makefile 1577 2009-04-25 08:02:52Z lion $

SUBDIRS = kernel libc rpc startup loader debug sbv dma graph math3d math packet draw erl erl-loader mpeg libgs libvux

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make
